#!/bin/bash

# どこかでエラーが発生した場合、スクリプトを終了する
set -e

# 現在のブランチ名を定義
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
readonly BRANCH_NAME

# master/main ブランチへのコミットを禁止
case "${BRANCH_NAME}" in
  master|main)
    echo -e "\033[31;22mNG\033[0m"
    echo -e "\033[31;22m================================================================"
    echo -e "${BRANCH_NAME}ブランチへのコミットは禁止されています。"
    echo -e "================================================================\033[0m"
    echo ""
    echo -e "\033[31;1mGit Hooks: pre-commit: NG\033[0m\n\n"
    exit 1
    ;;
esac

npx lint-staged
CI=true yarn test:pre-commit -o